name = "noscape-backend"
main = "src/index.ts"
compatibility_date = "2024-06-02"

[build]
command = "npm run build"

[[build.upload.rules]]
type = "JavaScript"
globs = ["src/index.ts"]

[build.upload]
format = "service-worker"
